### ISSUE TITLE
[Launch jog_arm] write simulation launch file

### ISSUE THREAD

**Issue by jschleicher** [PilzDE/pilz_teach#1]
* [jog_arm, currently in moveit_experimental](https://github.com/ros-planning/moveit) used for jogging the manipulator
best used together with
  [tork-a/fake_joint](https://github.com/tork-a/fake_joint) if testing jogging in a simulation environment.

**Comment by DamKoVosh** [comment]
Info: von moveit_experimental muss man nur das jog_arm_packet bauen

**Comment by Hardthof** [comment]
see branch feature/launch_jog_arm
