### ISSUE TITLE
[UI tests] refinements

### ISSUE THREAD

**Issue by jschleicher** [PilzDE/pilz_teach#22]
Implement changes for the second run

based on key_teleop:

- [x] Include jointwise and axiswise rotation in all bindings
- [x] Name rotation as rx ry rz everywhere
- [x] Axis rotation missing in description
- [x] Add max velocity: Speed button is always maxed speed, and normal speed is adjustable
- [x] Try using ctrl as speed button
- [x] Double-check correct units ([m/s] and [rad/s] are misleading)
- [x] Adjust the descriptions: Use tables for better structure, leave away quotation marks

**Comment by tobi-v** [comment]
The units are in [m/s] and [rad/s] and are reduced automatically if too high.
