### ISSUE TITLE
[6D-key_teleop] initial teleoperation implementation

### ISSUE THREAD

**Issue by jschleicher** [PilzDE/pilz_teach#6]
based on #1 

The virtual robot moves "somehow" via keyboard presses. This should implement / fork an initial keyboard control and show, what needs to be done in future PBIs.

Evaluate, if possible or already available
* robot stops on key-release
* single-joint jogging
* cartesian 6D jogging
* velocity scaling
* define other coordinate frame (like tcp cartesian jogging)

**Comment by DamKoVosh** [comment]
Evaluation:
Both variants need to be changed to use TwistStamped to work with jog_arm.
- ros-teleop/teleop_twist_keyboard
  - no real stop on key-releas (finishes the last move ~ ca 5 cm)
  - no single-joint-jogging
  - cartesian 6D jogging with pull requests (one of which has already transformation to needed StampedTwist)
  - something like velocity scaling (resends last twist with new scaling, even if it already finished => unexprected movement)
  - no other coordinate frames

- ros-teleop/teleop_tools
  - stop on key release (in SimpleKeyTeleop variant)
  - no single joint jogging
  - no 6D jogging
  - no velocity scaling
  - no definition of other coordinate frame
